name: Auto Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  auto-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get current version and commit
        id: version_info
        run: |
          CURRENT_VERSION=$(grep -oP '<Version>\K[^<]+' SoftArchitecture.csproj)
          COMMIT_HASH=$(git rev-parse --short HEAD)
          RELEASE_VERSION="${CURRENT_VERSION}-${COMMIT_HASH}"
          echo "current_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          echo "commit_hash=$COMMIT_HASH" >> $GITHUB_OUTPUT
          echo "release_version=$RELEASE_VERSION" >> $GITHUB_OUTPUT
          echo "Current version: $CURRENT_VERSION"
          echo "Commit hash: $COMMIT_HASH"
          echo "Release version: $RELEASE_VERSION"

      - name: Create release zip
        run: |
          # Create zip file from publish folder
          cd bin/publish
          zip -r "../SoftArchitecture-v${{ steps.version_info.outputs.release_version }}.zip" .
          cd ../..

      - name: Create Release
        run: |
          gh release create "${{ steps.version_info.outputs.release_version }}" \
            --title "SoftArchitecture v${{ steps.version_info.outputs.release_version }}" \
            --notes "## SoftArchitecture v${{ steps.version_info.outputs.release_version }}

            ### What's New
            - Professional project management tool for software developers

            ### Installation
            1. Download the zip file
            2. Extract the contents
            3. Run \`setup.exe\` to install the application

            ### System Requirements
            - Windows 10 or later
            - .NET 8.0 Runtime" \
            --draft=false \
            --prerelease=false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        run: |
          gh release upload "${{ steps.version_info.outputs.release_version }}" \
            "bin/SoftArchitecture-v${{ steps.version_info.outputs.release_version }}.zip" \
            --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
