name: Auto Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  auto-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get current version
        id: current_version
        run: |
          CURRENT_VERSION=$(grep -oP '<Version>\K[^<]+' SoftArchitecture.csproj)
          echo "current_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          echo "Current version: $CURRENT_VERSION"

      - name: Create release zip
        run: |
          # Create zip file from publish folder
          cd bin/publish
          zip -r "../SoftArchitecture-v${{ steps.current_version.outputs.current_version }}.zip" .
          cd ../..

      - name: Create Release
        id: create_release
        run: |
          # Check if release already exists
          if gh release view "v${{ steps.current_version.outputs.current_version }}" >/dev/null 2>&1; then
            echo "Release v${{ steps.current_version.outputs.current_version }} already exists"
            exit 0
          fi

          # Create new release
          gh release create "v${{ steps.current_version.outputs.current_version }}" \
            --title "SoftArchitecture v${{ steps.current_version.outputs.current_version }}" \
            --notes "## SoftArchitecture v${{ steps.current_version.outputs.current_version }}

            ### What's New
            - Professional project management tool for software developers

            ### Installation
            1. Download the zip file
            2. Extract the contents
            3. Run \`setup.exe\` to install the application

            ### System Requirements
            - Windows 10 or later
            - .NET 8.0 Runtime" \
            --draft=false \
            --prerelease=false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        run: |
          gh release upload "v${{ steps.current_version.outputs.current_version }}" \
            "bin/SoftArchitecture-v${{ steps.current_version.outputs.current_version }}.zip" \
            --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
