name: Auto Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  releases: write

jobs:
  auto-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get next release number
        id: release_number
        run: |
          # Get the latest release number
          LATEST_RELEASE=$(gh release list --limit 1 --json tagName | jq -r '.[0].tagName // "v0"')
          echo "Latest release: $LATEST_RELEASE"

          # Extract number and increment
          if [[ $LATEST_RELEASE =~ v([0-9]+) ]]; then
            NEXT_NUMBER=$((BASH_REMATCH[1] + 1))
          else
            NEXT_NUMBER=1
          fi

          RELEASE_VERSION="v$NEXT_NUMBER"
          echo "release_version=$RELEASE_VERSION" >> $GITHUB_OUTPUT
          echo "Next release: $RELEASE_VERSION"

      - name: Create release zip
        run: |
          # Create zip file from publish folder
          cd bin/publish
          zip -r "../SoftArchitecture-${{ steps.release_number.outputs.release_version }}.zip" .
          cd ../..

      - name: Create Release
        run: |
          gh release create "${{ steps.release_number.outputs.release_version }}" \
            --title "SoftArchitecture ${{ steps.release_number.outputs.release_version }}" \
            --notes "## SoftArchitecture ${{ steps.release_number.outputs.release_version }}

            ### What's New
            - Professional project management tool for software developers

            ### Installation
            1. Download the zip file
            2. Extract the contents
            3. Run \`setup.exe\` to install the application

            ### System Requirements
            - Windows 10 or later
            - .NET 8.0 Runtime" \
            --draft=false \
            --prerelease=false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        run: |
          gh release upload "${{ steps.release_number.outputs.release_version }}" \
            "bin/SoftArchitecture-${{ steps.release_number.outputs.release_version }}.zip" \
            --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
